### PR TITLE
Allow interaction with codemirror object from parent.

### PR DESCRIPTION
**Pull request by JodusNodus**
- Allow parent component to interact with code mirror instance created in the child.
- Updated build

I needed this for my project and i thought others might need it too.

Cheers, 🎄

### CODE REVIEW

**Comment by JedWatson** [comment]
Thanks @JodusNodus, I'll add a check to make sure `interact` is defined, but otherwise looks good :smiley:

**Comment by JedWatson** [comment]
Actually... _edit_

Wouldn't it be cleaner (and more React-y) to just use a `ref` for the `react-codemirror` component, and use its `getCodeMirror` method on the parent component's `componentDidMount` to interact with the `CodeMirror` instance?

This basically provides the same effect without the need for an `interact` prop:

```
// ...
componentDidMount () {
  this.refs.cm.getCodeMirror.doSomething();
},
render () {
  return <CodeMirror ref="cm" />
}
// ...
```

**Comment by JodusNodus** [comment]
Indeed that looks better. Just tested that and that seems to work great. Thanks, didn't know you could acces the component methods using the reference. :+1:

**Comment by JedWatson** [comment]
Glad that resolves it - I've rolled the change back and updated the docs to make it clearer.

**Comment by guidobouman** [comment]
This is actually still in the example code: https://github.com/JedWatson/react-codemirror/blob/master/example/src/example.js#L39 && https://github.com/JedWatson/react-codemirror/blob/master/example/src/example.js#L56

**Pull request merged**
