### PR TITLE
No longer debounce componentWillReceiveProps #106

### LINKED ISSUE #106: Code mirror value doesn't update with state change in v1.0.0
Changing props.value does not re-render code mirror. This is a new issue in v1.0.0, previously this worked.  Changing props.value via the onChange event works fine, but programmatically changing props.value does not call a re-render.

This can be reproduced with the following code.
````
class Editor extends Component {
    constructor() {
        super();
        this.state = { value: 'abc' };
    }

    render() {
        const { value } = this.state;
        console.log(value);
        return (
            <div>
                <CodeMirror value={value} />
                <button onClick={() => this.setState({ value: 'def' })}>Click to change value</button>
            </div>
        );
    }
}
````

This appears like it may have something to do with this change listed in the history file: ````fixed; Only updates the CodeMirror value if props.value has changed````.

### PR DESCRIPTION
**Pull request by ovidiuch**
Fixes #106

### CODE REVIEW

**Comment by alexandro81** [comment]
Hi @skidding, just wanted to know if you are plan to check this in soon, since IMHO it's not a good idea to debounce a lifecycle event.

**Comment by ovidiuch** [comment]
@alexandro81 it's not up to me since I don't have write nor publish rights on this project. See [this thread](https://github.com/JedWatson/react-codemirror/issues/106#issuecomment-301675526) for now.

**Comment by alexandro81** [comment]
Got it, thanks!

**Comment by alexandro81** [comment]
@JedWatson is there any blocker for this? It would be nice to have the fixed checked-in, unless you think there's something wrong in the PR?

**Comment by rickhanlonii** [comment]
Bump

**Comment by rocktavious** [comment]
Double Bump!

**Comment by danez** [comment]
//cc @JedWatson

**Comment by besh** [comment]
@JedWatson If this gets merged, can it be part of a minor release? All our team needed recently was fixing the 15.5 deprecation warnings but that was bundled with the v1 release with a lot of other changes.

**Comment by budiantotan** [comment]
bump!

**Comment by inoas** [comment]
This is another PR aiming at the same issue https://github.com/JedWatson/react-codemirror/pull/122

**Comment by christopherdro** [comment]
Confirming this fixes #106.

/cc @JedWatson

**Comment by scniro** [comment]
[react-codemirror2](https://github.com/scniro/react-codemirror2). Help me build it however we want. Let's move on - we've been waiting _months_. Why are you all still holding out?

**Comment by inoas** [comment]
Maybe his subscription here is off, so I felt free and asked him directly: https://twitter.com/In0as/status/896357219473780737

**Comment by lin-credible** [comment]
:tulip: :+1: :rose:

**Review by windhamwong — APPROVED** [review]
Tested out and this works perfectly.

**Comment by devonbl** [comment]
@JedWatson bump <3<3<3

**Comment by scniro** [comment]
@devonbl [react-codemirror2](https://github.com/scniro/react-codemirror2) <3<3<3

**Comment by inoas** [comment]
So the thing is:

# 1. Can @JedWatson review and merge; Alternatively give @skidding merge privileges?
# 2. If not 1. - Can we agree on one fork and move the community over there and continue over there? Also please deprecate react-codemirror?
# 3. Candidates
* **https://github.com/scniro/react-codemirror2**
* ~https://github.com/skidding/react-codemirror/tree/106-fix-update~ author seems to be ok to use react-codemirror2 in future (if it works for him) - https://github.com/JedWatson/react-codemirror/issues/106#issuecomment-302674960

**Comment by inoas** [comment]
Edit: Please try https://github.com/scniro/react-codemirror2 instead.
That fork is maintained, available via npm and gathering stars.

**Pull request closed without merging**
