### PR TITLE
Make debounce specific to the instance

### PR DESCRIPTION
**Pull request by sslotsky**
Resubmission of #49 

Elected to resubmit rather than rebase because
1. Code was extremely stale
2. Easier to undo my changes to the `lib` folder, which I assume you don't want

Also noticed that #66 proposes the same change as this does, but it also needs rebasing. @JedWatson I'll leave it up to you which one you prefer, but assuming you use this one, let's get it before it goes stale again!

### CODE REVIEW

**Comment by obrok** [comment]
@JedWatson could you post a notification in this PR when/if you release this?

**Comment by chungeunkim** [comment]
+1

**Comment by sslotsky** [comment]
@JedWatson this has gone stale again. Are you not watching this repo?

**Comment by alpacaaa** [comment]
Thanks @sslotsky for the patch. For anyone in need of a quick hack, here's what I'm using:
```
import debounce from 'lodash.debounce'

class PatchedCodeMirror extends CodeMirror {
  constructor() {
    super()
    this.handleUpdate = debounce(function(nextProps) {
      if (this.codeMirror && nextProps.value !== undefined && this.codeMirror.getValue() !== nextProps.value) {
        this.codeMirror.setValue(nextProps.value)
      }
      if (typeof nextProps.options === 'object') {
        for (let optionName in nextProps.options) {
          if (nextProps.options.hasOwnProperty(optionName)) {
            this.codeMirror.setOption(optionName, nextProps.options[optionName])
          }
        }
      }
    }, 0)
  }

  componentWillReceiveProps(nextProps) {
    this.handleUpdate(nextProps)
  }
}
```

Hopefully this will get merged soon 😕

**Comment by JedWatson** [comment]
Hey @sslotsky sorry for the delay - I believe a valid fix for this has already been merged: see https://github.com/JedWatson/react-codemirror/blob/master/src/Codemirror.js#L39

```js
componentWillMount () {
	this.componentWillReceiveProps = debounce(this.componentWillReceiveProps, 0);
},
```

If that doesn't work for you, I'll replace it with the method in this PR - let me know.

Thanks!

**Comment by JedWatson** [comment]
by the way, I've just published 0.3.0 including a fix that _I think_ works

**Comment by alpacaaa** [comment]
@JedWatson can confirm `0.3.0` works as expected, thanks!

**Pull request closed without merging**
