### PR TITLE
Set new options only if their values are different from the old ones

### PR DESCRIPTION
**Pull request by attaboy**
This patch makes it possible to use react-codemirror with codemirror's lint plugin, which otherwise doesn't work (see #89 and #53). It does this by only re-setting options on the codemirror instance when the values differ from those already set. I added a set of basic "deep equal" tools to ensure that this works correctly.

### CODE REVIEW

**Comment by cacois** [comment]
Branch works well, and allows lint plugin to function. I recommend a merge of this PR.

**Comment by brucemcpherson** [comment]
Any idea when this v0.4.0 be published on npm?

**Comment by ktalebian** [comment]
Waiting for this to go out. Can we get an estimate when this will be merged and released?

**Comment by naheeyahh** [comment]
@JedWatson can you merge this?

**Comment by JedWatson** [comment]
Thanks for the fix @attaboy!

I've made similar changes directly because of conflicts, and introduced `lodash.isequal` rather than inlining the deep comparison methods to keep the source focused.

**Pull request closed without merging**
